### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by TDL77** [yaruslove/snake_func_activation#1]
Подскажи пожалуйста , я ее правильно тут применил .
Как то результаты прям совсем не гут , получается тут без нее даже лучше.
class MultipleRegression(nn.Module):
    def __init__(self, num_features):
        super(MultipleRegression, self).__init__()
        
        self.layer_1 = nn.Linear(num_features, 16)
        self.layer_2 = nn.Linear(16, 32)
        self.layer_3 = nn.Linear(32, 16)
        self.act_snake = Snake(16, 2)             # <<<----
        self.layer_out = nn.Linear(16, 1)
                
    def forward(self, inputs):
        x = self.layer_1(inputs)
        x = self.layer_2(x)
        x = self.layer_3(x)
        x = self.layer_out(x)
        return (x)

    def predict(self, test_inputs):
        x = self.layer_1(test_inputs)
        x = self.layer_2(x)
        x = self.layer_3(x)
        x = self.act_snake(x)                       # <<<----
        x = self.layer_out(x)
        return (x)

**Comment by yaruslove** [comment]
1. Конфигурирование сети как последовательность линейных слоев nn.Linear(num_features, 16) => nn.Linear(16, 32) => nn.Linear(32, 16) эквивалентна просто перемножению подряд нескольких матриц, а перемножения ряда матриц 2-ух и более например 3 4ех эквиваленто простому перемножению двух матриц => обычное линейное преобразование. Нужно обьязательно добавлять слои активации например Relu в промежуток между линейными слоями


2. Сама функция act_snake по моим в большинстве случаев особо не помогла где-то даже ухудщила. Поэтому где нет явных периодических зависимостей лучше использовать классические методы линейную регрессию, деревья, бустинг итд
